name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch: {}

jobs:
  Job:
    name: Node.js
    uses: artusjs/github-actions/.github/workflows/node-test.yml@v1
    with:
      os: 'ubuntu-latest'
      version: '14, 16, 18'
      install: |
        tar xf zookeeper-3.4.6.tar.gz
        mv zookeeper-3.4.6/conf/zoo_sample.cfg zookeeper-3.4.6/conf/zoo.cfg
        ./zookeeper-3.4.6/bin/zkServer.sh start
        npm i --no-package-lock --no-fund
